//  (C) Copyright [2018-2022] Hewlett Packard Enterprise Development LP
//  Note: File corresponds to AOS 8.10.x.x release

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: aruba-iot-sb-config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This topic can be used to override some of the parameters in the iot-transport-profile
type TransportConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The reporting interval for NB telemetry messages.
	// The period is measured in seconds and cannot be 0
	ReportingPeriod *uint32 `protobuf:"varint,1,opt,name=reportingPeriod" json:"reportingPeriod,omitempty"`
	// The Cell Size in whole meters
	CellSize *uint32 `protobuf:"varint,2,opt,name=cellSize" json:"cellSize,omitempty"`
}

func (x *TransportConfig) Reset() {
	*x = TransportConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportConfig) ProtoMessage() {}

func (x *TransportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportConfig.ProtoReflect.Descriptor instead.
func (*TransportConfig) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_config_proto_rawDescGZIP(), []int{0}
}

func (x *TransportConfig) GetReportingPeriod() uint32 {
	if x != nil && x.ReportingPeriod != nil {
		return *x.ReportingPeriod
	}
	return 0
}

func (x *TransportConfig) GetCellSize() uint32 {
	if x != nil && x.CellSize != nil {
		return *x.CellSize
	}
	return 0
}

var File_aruba_iot_sb_config_proto protoreflect.FileDescriptor

var file_aruba_iot_sb_config_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x73, 0x62, 0x2d, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x75,
	0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x22, 0x57, 0x0a, 0x0f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x28, 0x0a, 0x0f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x65, 0x6c,
	0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x65, 0x6c,
	0x6c, 0x53, 0x69, 0x7a, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x6c, 0x75, 0x62, 0x64, 0x75, 0x62, 0x2e,
	0x6e, 0x6c, 0x2f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f,
}

var (
	file_aruba_iot_sb_config_proto_rawDescOnce sync.Once
	file_aruba_iot_sb_config_proto_rawDescData = file_aruba_iot_sb_config_proto_rawDesc
)

func file_aruba_iot_sb_config_proto_rawDescGZIP() []byte {
	file_aruba_iot_sb_config_proto_rawDescOnce.Do(func() {
		file_aruba_iot_sb_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_aruba_iot_sb_config_proto_rawDescData)
	})
	return file_aruba_iot_sb_config_proto_rawDescData
}

var file_aruba_iot_sb_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aruba_iot_sb_config_proto_goTypes = []any{
	(*TransportConfig)(nil), // 0: aruba_telemetry.TransportConfig
}
var file_aruba_iot_sb_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aruba_iot_sb_config_proto_init() }
func file_aruba_iot_sb_config_proto_init() {
	if File_aruba_iot_sb_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aruba_iot_sb_config_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TransportConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aruba_iot_sb_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aruba_iot_sb_config_proto_goTypes,
		DependencyIndexes: file_aruba_iot_sb_config_proto_depIdxs,
		MessageInfos:      file_aruba_iot_sb_config_proto_msgTypes,
	}.Build()
	File_aruba_iot_sb_config_proto = out.File
	file_aruba_iot_sb_config_proto_rawDesc = nil
	file_aruba_iot_sb_config_proto_goTypes = nil
	file_aruba_iot_sb_config_proto_depIdxs = nil
}
