//  (C) Copyright [2018-2022] Hewlett Packard Enterprise Development LP
//  Note: File corresponds to AOS 8.10.x.x release

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: aruba-iot-nb-status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum values related to BLE SB API connection updates
type StatusValue int32

const (
	StatusValue_deviceDisconnected StatusValue = 0
	StatusValue_inactivityTimeout  StatusValue = 1
	StatusValue_connectionUpdate   StatusValue = 2
)

// Enum value maps for StatusValue.
var (
	StatusValue_name = map[int32]string{
		0: "deviceDisconnected",
		1: "inactivityTimeout",
		2: "connectionUpdate",
	}
	StatusValue_value = map[string]int32{
		"deviceDisconnected": 0,
		"inactivityTimeout":  1,
		"connectionUpdate":   2,
	}
)

func (x StatusValue) Enum() *StatusValue {
	p := new(StatusValue)
	*p = x
	return p
}

func (x StatusValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusValue) Descriptor() protoreflect.EnumDescriptor {
	return file_aruba_iot_nb_status_proto_enumTypes[0].Descriptor()
}

func (StatusValue) Type() protoreflect.EnumType {
	return &file_aruba_iot_nb_status_proto_enumTypes[0]
}

func (x StatusValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StatusValue) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StatusValue(num)
	return nil
}

// Deprecated: Use StatusValue.Descriptor instead.
func (StatusValue) EnumDescriptor() ([]byte, []int) {
	return file_aruba_iot_nb_status_proto_rawDescGZIP(), []int{0}
}

type ConnUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The negotiated MTU Value between BLE central and peripheral
	MtuValue *uint32 `protobuf:"varint,1,opt,name=mtu_value,json=mtuValue" json:"mtu_value,omitempty"`
}

func (x *ConnUpdate) Reset() {
	*x = ConnUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_nb_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnUpdate) ProtoMessage() {}

func (x *ConnUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_nb_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnUpdate.ProtoReflect.Descriptor instead.
func (*ConnUpdate) Descriptor() ([]byte, []int) {
	return file_aruba_iot_nb_status_proto_rawDescGZIP(), []int{0}
}

func (x *ConnUpdate) GetMtuValue() uint32 {
	if x != nil && x.MtuValue != nil {
		return *x.MtuValue
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Refers to the MAC address of the end device. Typically a 6 byte BLE MAC or 8 byte Zigbee MAC
	DeviceMac []byte `protobuf:"bytes,1,opt,name=deviceMac" json:"deviceMac,omitempty"`
	// Status enum from above
	Status *StatusValue `protobuf:"varint,2,opt,name=status,enum=aruba_telemetry.StatusValue" json:"status,omitempty"`
	// Optional additional freeform information
	StatusString *string `protobuf:"bytes,3,opt,name=statusString" json:"statusString,omitempty"`
	// Connection update information
	ConnUpdate *ConnUpdate `protobuf:"bytes,4,opt,name=connUpdate" json:"connUpdate,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_nb_status_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_nb_status_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_aruba_iot_nb_status_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetDeviceMac() []byte {
	if x != nil {
		return x.DeviceMac
	}
	return nil
}

func (x *Status) GetStatus() StatusValue {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return StatusValue_deviceDisconnected
}

func (x *Status) GetStatusString() string {
	if x != nil && x.StatusString != nil {
		return *x.StatusString
	}
	return ""
}

func (x *Status) GetConnUpdate() *ConnUpdate {
	if x != nil {
		return x.ConnUpdate
	}
	return nil
}

var File_aruba_iot_nb_status_proto protoreflect.FileDescriptor

var file_aruba_iot_nb_status_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x6e, 0x62, 0x2d, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x75,
	0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x22, 0x29, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x74,
	0x75, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d,
	0x74, 0x75, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xbd, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x63,
	0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1c, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x3b, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2a, 0x52, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x00, 0x12, 0x15,
	0x0a, 0x11, 0x69, 0x6e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x10, 0x02, 0x42, 0x1b, 0x5a, 0x19, 0x6c,
	0x75, 0x62, 0x64, 0x75, 0x62, 0x2e, 0x6e, 0x6c, 0x2f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69,
	0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_aruba_iot_nb_status_proto_rawDescOnce sync.Once
	file_aruba_iot_nb_status_proto_rawDescData = file_aruba_iot_nb_status_proto_rawDesc
)

func file_aruba_iot_nb_status_proto_rawDescGZIP() []byte {
	file_aruba_iot_nb_status_proto_rawDescOnce.Do(func() {
		file_aruba_iot_nb_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_aruba_iot_nb_status_proto_rawDescData)
	})
	return file_aruba_iot_nb_status_proto_rawDescData
}

var file_aruba_iot_nb_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aruba_iot_nb_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aruba_iot_nb_status_proto_goTypes = []any{
	(StatusValue)(0),   // 0: aruba_telemetry.statusValue
	(*ConnUpdate)(nil), // 1: aruba_telemetry.ConnUpdate
	(*Status)(nil),     // 2: aruba_telemetry.Status
}
var file_aruba_iot_nb_status_proto_depIdxs = []int32{
	0, // 0: aruba_telemetry.Status.status:type_name -> aruba_telemetry.statusValue
	1, // 1: aruba_telemetry.Status.connUpdate:type_name -> aruba_telemetry.ConnUpdate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aruba_iot_nb_status_proto_init() }
func file_aruba_iot_nb_status_proto_init() {
	if File_aruba_iot_nb_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aruba_iot_nb_status_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ConnUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_nb_status_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aruba_iot_nb_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aruba_iot_nb_status_proto_goTypes,
		DependencyIndexes: file_aruba_iot_nb_status_proto_depIdxs,
		EnumInfos:         file_aruba_iot_nb_status_proto_enumTypes,
		MessageInfos:      file_aruba_iot_nb_status_proto_msgTypes,
	}.Build()
	File_aruba_iot_nb_status_proto = out.File
	file_aruba_iot_nb_status_proto_rawDesc = nil
	file_aruba_iot_nb_status_proto_goTypes = nil
	file_aruba_iot_nb_status_proto_depIdxs = nil
}
