//  (C) Copyright [2018-2022] Hewlett Packard Enterprise Development LP
//  Note: File corresponds to AOS 8.10.x.x release

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: aruba-iot-nb-zb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Report/send APS data to server
type ZbNbReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// IEEE address of the device
	Mac []byte `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	// E2PC
	E2Pc *ZbE2PC `protobuf:"bytes,2,opt,name=e2pc" json:"e2pc,omitempty"`
	// Payload of report data
	Payload []byte `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
}

func (x *ZbNbReport) Reset() {
	*x = ZbNbReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_nb_zb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbNbReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbNbReport) ProtoMessage() {}

func (x *ZbNbReport) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_nb_zb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbNbReport.ProtoReflect.Descriptor instead.
func (*ZbNbReport) Descriptor() ([]byte, []int) {
	return file_aruba_iot_nb_zb_proto_rawDescGZIP(), []int{0}
}

func (x *ZbNbReport) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *ZbNbReport) GetE2Pc() *ZbE2PC {
	if x != nil {
		return x.E2Pc
	}
	return nil
}

func (x *ZbNbReport) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Used for send, write/action request
type ZbNbAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Request ID
	Reqid *string `protobuf:"bytes,1,opt,name=reqid" json:"reqid,omitempty"`
	// Indicate whether send, write/action request is successful
	Result *ZbResult `protobuf:"varint,2,opt,name=result,enum=aruba_telemetry.ZbResult" json:"result,omitempty"`
	// Indicate the code for failure
	Code *ZbAckCode `protobuf:"varint,3,opt,name=code,enum=aruba_telemetry.ZbAckCode" json:"code,omitempty"`
}

func (x *ZbNbAck) Reset() {
	*x = ZbNbAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_nb_zb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbNbAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbNbAck) ProtoMessage() {}

func (x *ZbNbAck) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_nb_zb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbNbAck.ProtoReflect.Descriptor instead.
func (*ZbNbAck) Descriptor() ([]byte, []int) {
	return file_aruba_iot_nb_zb_proto_rawDescGZIP(), []int{1}
}

func (x *ZbNbAck) GetReqid() string {
	if x != nil && x.Reqid != nil {
		return *x.Reqid
	}
	return ""
}

func (x *ZbNbAck) GetResult() ZbResult {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return ZbResult_SUCCEEDED
}

func (x *ZbNbAck) GetCode() ZbAckCode {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ZbAckCode_OK
}

// Used for read request
type ZbNbRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Request ID
	Reqid *string `protobuf:"bytes,1,opt,name=reqid" json:"reqid,omitempty"`
}

func (x *ZbNbRsp) Reset() {
	*x = ZbNbRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_nb_zb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbNbRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbNbRsp) ProtoMessage() {}

func (x *ZbNbRsp) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_nb_zb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbNbRsp.ProtoReflect.Descriptor instead.
func (*ZbNbRsp) Descriptor() ([]byte, []int) {
	return file_aruba_iot_nb_zb_proto_rawDescGZIP(), []int{2}
}

func (x *ZbNbRsp) GetReqid() string {
	if x != nil && x.Reqid != nil {
		return *x.Reqid
	}
	return ""
}

type NbZbMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Zigbee radio MAC
	RadioMac []byte `protobuf:"bytes,1,opt,name=radio_mac,json=radioMac" json:"radio_mac,omitempty"`
	// Report/send APS data
	Report *ZbNbReport `protobuf:"bytes,2,opt,name=report" json:"report,omitempty"`
	// Acknowledgement for send, write/action request
	Ack *ZbNbAck `protobuf:"bytes,3,opt,name=ack" json:"ack,omitempty"`
	// Response for read request
	Response *ZbNbRsp `protobuf:"bytes,4,opt,name=response" json:"response,omitempty"`
}

func (x *NbZbMsg) Reset() {
	*x = NbZbMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_nb_zb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NbZbMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NbZbMsg) ProtoMessage() {}

func (x *NbZbMsg) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_nb_zb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NbZbMsg.ProtoReflect.Descriptor instead.
func (*NbZbMsg) Descriptor() ([]byte, []int) {
	return file_aruba_iot_nb_zb_proto_rawDescGZIP(), []int{3}
}

func (x *NbZbMsg) GetRadioMac() []byte {
	if x != nil {
		return x.RadioMac
	}
	return nil
}

func (x *NbZbMsg) GetReport() *ZbNbReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *NbZbMsg) GetAck() *ZbNbAck {
	if x != nil {
		return x.Ack
	}
	return nil
}

func (x *NbZbMsg) GetResponse() *ZbNbRsp {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_aruba_iot_nb_zb_proto protoreflect.FileDescriptor

var file_aruba_iot_nb_zb_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x6e, 0x62, 0x2d, 0x7a,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x1a, 0x18, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d,
	0x69, 0x6f, 0x74, 0x2d, 0x7a, 0x62, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0a, 0x5a, 0x62, 0x4e, 0x62, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d,
	0x61, 0x63, 0x12, 0x2b, 0x0a, 0x04, 0x65, 0x32, 0x70, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2e, 0x5a, 0x62, 0x45, 0x32, 0x50, 0x43, 0x52, 0x04, 0x65, 0x32, 0x70, 0x63, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x07, 0x5a, 0x62,
	0x4e, 0x62, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x61, 0x72,
	0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x5a, 0x62,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2e,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x61,
	0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x5a,
	0x62, 0x41, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x1f,
	0x0a, 0x07, 0x5a, 0x62, 0x4e, 0x62, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x22,
	0xbd, 0x01, 0x0a, 0x07, 0x4e, 0x62, 0x5a, 0x62, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x61, 0x64, 0x69, 0x6f, 0x5f, 0x6d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x72, 0x61, 0x64, 0x69, 0x6f, 0x4d, 0x61, 0x63, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61,
	0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x5a, 0x62, 0x4e, 0x62, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x2a, 0x0a,
	0x03, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x72, 0x75,
	0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x5a, 0x62, 0x4e,
	0x62, 0x41, 0x63, 0x6b, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x72,
	0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x5a, 0x62,
	0x4e, 0x62, 0x52, 0x73, 0x70, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1b, 0x5a, 0x19, 0x6c, 0x75, 0x62, 0x64, 0x75, 0x62, 0x2e, 0x6e, 0x6c, 0x2f, 0x61, 0x72, 0x75,
	0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_aruba_iot_nb_zb_proto_rawDescOnce sync.Once
	file_aruba_iot_nb_zb_proto_rawDescData = file_aruba_iot_nb_zb_proto_rawDesc
)

func file_aruba_iot_nb_zb_proto_rawDescGZIP() []byte {
	file_aruba_iot_nb_zb_proto_rawDescOnce.Do(func() {
		file_aruba_iot_nb_zb_proto_rawDescData = protoimpl.X.CompressGZIP(file_aruba_iot_nb_zb_proto_rawDescData)
	})
	return file_aruba_iot_nb_zb_proto_rawDescData
}

var file_aruba_iot_nb_zb_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aruba_iot_nb_zb_proto_goTypes = []any{
	(*ZbNbReport)(nil), // 0: aruba_telemetry.ZbNbReport
	(*ZbNbAck)(nil),    // 1: aruba_telemetry.ZbNbAck
	(*ZbNbRsp)(nil),    // 2: aruba_telemetry.ZbNbRsp
	(*NbZbMsg)(nil),    // 3: aruba_telemetry.NbZbMsg
	(*ZbE2PC)(nil),     // 4: aruba_telemetry.ZbE2PC
	(ZbResult)(0),      // 5: aruba_telemetry.ZbResult
	(ZbAckCode)(0),     // 6: aruba_telemetry.ZbAckCode
}
var file_aruba_iot_nb_zb_proto_depIdxs = []int32{
	4, // 0: aruba_telemetry.ZbNbReport.e2pc:type_name -> aruba_telemetry.ZbE2PC
	5, // 1: aruba_telemetry.ZbNbAck.result:type_name -> aruba_telemetry.ZbResult
	6, // 2: aruba_telemetry.ZbNbAck.code:type_name -> aruba_telemetry.ZbAckCode
	0, // 3: aruba_telemetry.NbZbMsg.report:type_name -> aruba_telemetry.ZbNbReport
	1, // 4: aruba_telemetry.NbZbMsg.ack:type_name -> aruba_telemetry.ZbNbAck
	2, // 5: aruba_telemetry.NbZbMsg.response:type_name -> aruba_telemetry.ZbNbRsp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_aruba_iot_nb_zb_proto_init() }
func file_aruba_iot_nb_zb_proto_init() {
	if File_aruba_iot_nb_zb_proto != nil {
		return
	}
	file_aruba_iot_zb_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aruba_iot_nb_zb_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ZbNbReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_nb_zb_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ZbNbAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_nb_zb_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ZbNbRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_nb_zb_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*NbZbMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aruba_iot_nb_zb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aruba_iot_nb_zb_proto_goTypes,
		DependencyIndexes: file_aruba_iot_nb_zb_proto_depIdxs,
		MessageInfos:      file_aruba_iot_nb_zb_proto_msgTypes,
	}.Build()
	File_aruba_iot_nb_zb_proto = out.File
	file_aruba_iot_nb_zb_proto_rawDesc = nil
	file_aruba_iot_nb_zb_proto_goTypes = nil
	file_aruba_iot_nb_zb_proto_depIdxs = nil
}
