//  (C) Copyright [2018-2022] Hewlett Packard Enterprise Development LP
//  Note: File corresponds to AOS 8.10.x.x release

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: aruba-iot-sb-zb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Send Zigbee APS data to remote device
type ZbSbSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Request ID: when this field exists, acknowledgement from AP is required.
	Reqid *string `protobuf:"bytes,1,opt,name=reqid" json:"reqid,omitempty"`
	// IEEE address of destination device
	Mac []byte `protobuf:"bytes,2,opt,name=mac" json:"mac,omitempty"`
	// Source/destionation endpoint, profile ID, cluster ID
	E2Pc *ZbE2PC `protobuf:"bytes,3,opt,name=e2pc" json:"e2pc,omitempty"`
	// Payload of APS data
	Payload []byte `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
}

func (x *ZbSbSend) Reset() {
	*x = ZbSbSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_zb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbSbSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbSbSend) ProtoMessage() {}

func (x *ZbSbSend) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_zb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbSbSend.ProtoReflect.Descriptor instead.
func (*ZbSbSend) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_zb_proto_rawDescGZIP(), []int{0}
}

func (x *ZbSbSend) GetReqid() string {
	if x != nil && x.Reqid != nil {
		return *x.Reqid
	}
	return ""
}

func (x *ZbSbSend) GetMac() []byte {
	if x != nil {
		return x.Mac
	}
	return nil
}

func (x *ZbSbSend) GetE2Pc() *ZbE2PC {
	if x != nil {
		return x.E2Pc
	}
	return nil
}

func (x *ZbSbSend) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Read request for information or configuration from AP or remote device
type ZbSbRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Request ID for read
	Reqid *string `protobuf:"bytes,1,opt,name=reqid" json:"reqid,omitempty"`
}

func (x *ZbSbRead) Reset() {
	*x = ZbSbRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_zb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbSbRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbSbRead) ProtoMessage() {}

func (x *ZbSbRead) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_zb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbSbRead.ProtoReflect.Descriptor instead.
func (*ZbSbRead) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_zb_proto_rawDescGZIP(), []int{1}
}

func (x *ZbSbRead) GetReqid() string {
	if x != nil && x.Reqid != nil {
		return *x.Reqid
	}
	return ""
}

// Write request for information or configuration to AP or remote device
type ZbSbWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Request ID for write
	Reqid *string `protobuf:"bytes,1,opt,name=reqid" json:"reqid,omitempty"`
}

func (x *ZbSbWrite) Reset() {
	*x = ZbSbWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_zb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbSbWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbSbWrite) ProtoMessage() {}

func (x *ZbSbWrite) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_zb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbSbWrite.ProtoReflect.Descriptor instead.
func (*ZbSbWrite) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_zb_proto_rawDescGZIP(), []int{2}
}

func (x *ZbSbWrite) GetReqid() string {
	if x != nil && x.Reqid != nil {
		return *x.Reqid
	}
	return ""
}

// Action request for AP or remote device
type ZbSbAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Request ID for action
	Reqid *string `protobuf:"bytes,1,opt,name=reqid" json:"reqid,omitempty"`
}

func (x *ZbSbAction) Reset() {
	*x = ZbSbAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_zb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbSbAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbSbAction) ProtoMessage() {}

func (x *ZbSbAction) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_zb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbSbAction.ProtoReflect.Descriptor instead.
func (*ZbSbAction) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_zb_proto_rawDescGZIP(), []int{3}
}

func (x *ZbSbAction) GetReqid() string {
	if x != nil && x.Reqid != nil {
		return *x.Reqid
	}
	return ""
}

type ZbSbReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Read request
	Read *ZbSbRead `protobuf:"bytes,1,opt,name=read" json:"read,omitempty"`
	// Write request
	Write *ZbSbWrite `protobuf:"bytes,2,opt,name=write" json:"write,omitempty"`
	// Action request
	Action *ZbSbAction `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
}

func (x *ZbSbReq) Reset() {
	*x = ZbSbReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_zb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbSbReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbSbReq) ProtoMessage() {}

func (x *ZbSbReq) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_zb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbSbReq.ProtoReflect.Descriptor instead.
func (*ZbSbReq) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_zb_proto_rawDescGZIP(), []int{4}
}

func (x *ZbSbReq) GetRead() *ZbSbRead {
	if x != nil {
		return x.Read
	}
	return nil
}

func (x *ZbSbReq) GetWrite() *ZbSbWrite {
	if x != nil {
		return x.Write
	}
	return nil
}

func (x *ZbSbReq) GetAction() *ZbSbAction {
	if x != nil {
		return x.Action
	}
	return nil
}

type SbZbMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Zigbee radio IEEE MAC which is 8 octets
	RadioMac []byte `protobuf:"bytes,1,opt,name=radio_mac,json=radioMac" json:"radio_mac,omitempty"`
	// Send APS data
	Send *ZbSbSend `protobuf:"bytes,2,opt,name=send" json:"send,omitempty"`
	// Request to AP or remote Zigbee device
	Request *ZbSbReq `protobuf:"bytes,3,opt,name=request" json:"request,omitempty"`
}

func (x *SbZbMsg) Reset() {
	*x = SbZbMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_zb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SbZbMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SbZbMsg) ProtoMessage() {}

func (x *SbZbMsg) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_zb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SbZbMsg.ProtoReflect.Descriptor instead.
func (*SbZbMsg) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_zb_proto_rawDescGZIP(), []int{5}
}

func (x *SbZbMsg) GetRadioMac() []byte {
	if x != nil {
		return x.RadioMac
	}
	return nil
}

func (x *SbZbMsg) GetSend() *ZbSbSend {
	if x != nil {
		return x.Send
	}
	return nil
}

func (x *SbZbMsg) GetRequest() *ZbSbReq {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_aruba_iot_sb_zb_proto protoreflect.FileDescriptor

var file_aruba_iot_sb_zb_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x73, 0x62, 0x2d, 0x7a,
	0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x1a, 0x18, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d,
	0x69, 0x6f, 0x74, 0x2d, 0x7a, 0x62, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x79, 0x0a, 0x08, 0x5a, 0x62, 0x53, 0x62, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72,
	0x65, 0x71, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x03, 0x6d, 0x61, 0x63, 0x12, 0x2b, 0x0a, 0x04, 0x65, 0x32, 0x70, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x5a, 0x62, 0x45, 0x32, 0x50, 0x43, 0x52, 0x04, 0x65,
	0x32, 0x70, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x20, 0x0a,
	0x08, 0x5a, 0x62, 0x53, 0x62, 0x52, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x22,
	0x21, 0x0a, 0x09, 0x5a, 0x62, 0x53, 0x62, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x65, 0x71, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71,
	0x69, 0x64, 0x22, 0x22, 0x0a, 0x0a, 0x5a, 0x62, 0x53, 0x62, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x72, 0x65, 0x71, 0x69, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x07, 0x5a, 0x62, 0x53, 0x62, 0x52,
	0x65, 0x71, 0x12, 0x2d, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2e, 0x5a, 0x62, 0x53, 0x62, 0x52, 0x65, 0x61, 0x64, 0x52, 0x04, 0x72, 0x65, 0x61,
	0x64, 0x12, 0x30, 0x0a, 0x05, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2e, 0x5a, 0x62, 0x53, 0x62, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x05, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x12, 0x33, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x5a, 0x62, 0x53, 0x62, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x07, 0x53, 0x62, 0x5a,
	0x62, 0x4d, 0x73, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x61, 0x64, 0x69, 0x6f, 0x5f, 0x6d, 0x61,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x61, 0x64, 0x69, 0x6f, 0x4d, 0x61,
	0x63, 0x12, 0x2d, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x2e, 0x5a, 0x62, 0x53, 0x62, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x64,
	0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x74, 0x72, 0x79, 0x2e, 0x5a, 0x62, 0x53, 0x62, 0x52, 0x65, 0x71, 0x52, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x1b, 0x5a, 0x19, 0x6c, 0x75, 0x62, 0x64, 0x75, 0x62, 0x2e, 0x6e,
	0x6c, 0x2f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f,
}

var (
	file_aruba_iot_sb_zb_proto_rawDescOnce sync.Once
	file_aruba_iot_sb_zb_proto_rawDescData = file_aruba_iot_sb_zb_proto_rawDesc
)

func file_aruba_iot_sb_zb_proto_rawDescGZIP() []byte {
	file_aruba_iot_sb_zb_proto_rawDescOnce.Do(func() {
		file_aruba_iot_sb_zb_proto_rawDescData = protoimpl.X.CompressGZIP(file_aruba_iot_sb_zb_proto_rawDescData)
	})
	return file_aruba_iot_sb_zb_proto_rawDescData
}

var file_aruba_iot_sb_zb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aruba_iot_sb_zb_proto_goTypes = []any{
	(*ZbSbSend)(nil),   // 0: aruba_telemetry.ZbSbSend
	(*ZbSbRead)(nil),   // 1: aruba_telemetry.ZbSbRead
	(*ZbSbWrite)(nil),  // 2: aruba_telemetry.ZbSbWrite
	(*ZbSbAction)(nil), // 3: aruba_telemetry.ZbSbAction
	(*ZbSbReq)(nil),    // 4: aruba_telemetry.ZbSbReq
	(*SbZbMsg)(nil),    // 5: aruba_telemetry.SbZbMsg
	(*ZbE2PC)(nil),     // 6: aruba_telemetry.ZbE2PC
}
var file_aruba_iot_sb_zb_proto_depIdxs = []int32{
	6, // 0: aruba_telemetry.ZbSbSend.e2pc:type_name -> aruba_telemetry.ZbE2PC
	1, // 1: aruba_telemetry.ZbSbReq.read:type_name -> aruba_telemetry.ZbSbRead
	2, // 2: aruba_telemetry.ZbSbReq.write:type_name -> aruba_telemetry.ZbSbWrite
	3, // 3: aruba_telemetry.ZbSbReq.action:type_name -> aruba_telemetry.ZbSbAction
	0, // 4: aruba_telemetry.SbZbMsg.send:type_name -> aruba_telemetry.ZbSbSend
	4, // 5: aruba_telemetry.SbZbMsg.request:type_name -> aruba_telemetry.ZbSbReq
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_aruba_iot_sb_zb_proto_init() }
func file_aruba_iot_sb_zb_proto_init() {
	if File_aruba_iot_sb_zb_proto != nil {
		return
	}
	file_aruba_iot_zb_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aruba_iot_sb_zb_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ZbSbSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_sb_zb_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ZbSbRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_sb_zb_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ZbSbWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_sb_zb_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ZbSbAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_sb_zb_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ZbSbReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_sb_zb_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SbZbMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aruba_iot_sb_zb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aruba_iot_sb_zb_proto_goTypes,
		DependencyIndexes: file_aruba_iot_sb_zb_proto_depIdxs,
		MessageInfos:      file_aruba_iot_sb_zb_proto_msgTypes,
	}.Build()
	File_aruba_iot_sb_zb_proto = out.File
	file_aruba_iot_sb_zb_proto_rawDesc = nil
	file_aruba_iot_sb_zb_proto_goTypes = nil
	file_aruba_iot_sb_zb_proto_depIdxs = nil
}
