//  (C) Copyright [2018-2022] Hewlett Packard Enterprise Development LP
//  Note: File corresponds to AOS 8.10.x.x release

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: aruba-iot-sb-action.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Method of security authentication
type AuthenticationMethod int32

const (
	// legacy: no mitm
	AuthenticationMethod_none AuthenticationMethod = 0
	// legacy: mitm, passkey
	AuthenticationMethod_passkey AuthenticationMethod = 1
	// legacy: mitm, keyOob
	AuthenticationMethod_oob AuthenticationMethod = 2
	// lesc: no mitm
	AuthenticationMethod_lescNone AuthenticationMethod = 3
	// lesc: mitm, passkey
	AuthenticationMethod_lescPasskey AuthenticationMethod = 4
	// lesc: mitm, keyOob
	AuthenticationMethod_lescOob AuthenticationMethod = 5
)

// Enum value maps for AuthenticationMethod.
var (
	AuthenticationMethod_name = map[int32]string{
		0: "none",
		1: "passkey",
		2: "oob",
		3: "lescNone",
		4: "lescPasskey",
		5: "lescOob",
	}
	AuthenticationMethod_value = map[string]int32{
		"none":        0,
		"passkey":     1,
		"oob":         2,
		"lescNone":    3,
		"lescPasskey": 4,
		"lescOob":     5,
	}
)

func (x AuthenticationMethod) Enum() *AuthenticationMethod {
	p := new(AuthenticationMethod)
	*p = x
	return p
}

func (x AuthenticationMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthenticationMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_aruba_iot_sb_action_proto_enumTypes[0].Descriptor()
}

func (AuthenticationMethod) Type() protoreflect.EnumType {
	return &file_aruba_iot_sb_action_proto_enumTypes[0]
}

func (x AuthenticationMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AuthenticationMethod) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AuthenticationMethod(num)
	return nil
}

// Deprecated: Use AuthenticationMethod.Descriptor instead.
func (AuthenticationMethod) EnumDescriptor() ([]byte, []int) {
	return file_aruba_iot_sb_action_proto_rawDescGZIP(), []int{0}
}

// Security authentication
type Authentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Reuired field. Specifiy which method is used for authentication
	Method *AuthenticationMethod `protobuf:"varint,1,opt,name=method,enum=aruba_telemetry.AuthenticationMethod" json:"method,omitempty"`
	// Whether bonding is enabled, which also depends on peer's bond
	Bonding *bool `protobuf:"varint,2,opt,name=bonding" json:"bonding,omitempty"`
	// Whether passkey is used. Passkey is  6 numeric digits (‘0’ - ‘9’)
	// ‘0’ will be prefixed if length of passkey is less than 6
	// Required when method is 'passkey' or 'lescPasskey'
	Passkey *string `protobuf:"bytes,3,opt,name=passkey" json:"passkey,omitempty"`
	// 16-bytes hexadecimal key. 0 will be prefixed if its length is less than 16
	// This is required when method is 'oob' or 'lescOob'
	KeyOob []byte `protobuf:"bytes,4,opt,name=keyOob" json:"keyOob,omitempty"`
	// 16-bytes hexadecimal key. 0 will be prefixed if its length is less than 16
	// This is required when lesc is used, and peer uses the server's keyOwn or passkey is used
	KeyOwn []byte `protobuf:"bytes,5,opt,name=keyOwn" json:"keyOwn,omitempty"`
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_action_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_action_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_action_proto_rawDescGZIP(), []int{0}
}

func (x *Authentication) GetMethod() AuthenticationMethod {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return AuthenticationMethod_none
}

func (x *Authentication) GetBonding() bool {
	if x != nil && x.Bonding != nil {
		return *x.Bonding
	}
	return false
}

func (x *Authentication) GetPasskey() string {
	if x != nil && x.Passkey != nil {
		return *x.Passkey
	}
	return ""
}

func (x *Authentication) GetKeyOob() []byte {
	if x != nil {
		return x.KeyOob
	}
	return nil
}

func (x *Authentication) GetKeyOwn() []byte {
	if x != nil {
		return x.KeyOwn
	}
	return nil
}

// Actions are instructions for the AP
type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identifier for the action. The sender needs to remember this id while the action is being executed.
	// The same action ID is included in the action results message, so that the sender can correlate
	// the results with the outrstanding action request. Max of 256 characters, remaining will be truncated
	ActionId *string `protobuf:"bytes,1,opt,name=actionId" json:"actionId,omitempty"`
	// Type of action to be executed
	Type *ActionType `protobuf:"varint,2,opt,name=type,enum=aruba_telemetry.ActionType" json:"type,omitempty"`
	// Refers to the MAC address of the end device. Typically a 6 byte BLE MAC or 8 byte Zigbee MAC
	DeviceMac []byte `protobuf:"bytes,3,opt,name=deviceMac" json:"deviceMac,omitempty"`
	// service UUID for BLE GATT read/write/notify Actions
	ServiceUuid []byte `protobuf:"bytes,4,opt,name=serviceUuid" json:"serviceUuid,omitempty"`
	// characteristic UUID for BLE GATT read/write/notify Actions
	CharacteristicUuid []byte `protobuf:"bytes,5,opt,name=characteristicUuid" json:"characteristicUuid,omitempty"`
	// maximum allotted time for the action to complete (in whole seconds)
	TimeOut *uint32 `protobuf:"varint,6,opt,name=timeOut" json:"timeOut,omitempty"`
	// Value to be used in write Actions
	Value []byte `protobuf:"bytes,7,opt,name=value" json:"value,omitempty"`
	// Authentication for pairing and encryption
	Authentication *Authentication `protobuf:"bytes,8,opt,name=authentication" json:"authentication,omitempty"`
	// Encryption for bonded devices
	BondingKey *BleBondingKey `protobuf:"bytes,9,opt,name=bondingKey" json:"bondingKey,omitempty"`
	// Multiple apb support
	ApbMac []byte `protobuf:"bytes,10,opt,name=apbMac" json:"apbMac,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_sb_action_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_sb_action_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_aruba_iot_sb_action_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetActionId() string {
	if x != nil && x.ActionId != nil {
		return *x.ActionId
	}
	return ""
}

func (x *Action) GetType() ActionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ActionType_bleConnect
}

func (x *Action) GetDeviceMac() []byte {
	if x != nil {
		return x.DeviceMac
	}
	return nil
}

func (x *Action) GetServiceUuid() []byte {
	if x != nil {
		return x.ServiceUuid
	}
	return nil
}

func (x *Action) GetCharacteristicUuid() []byte {
	if x != nil {
		return x.CharacteristicUuid
	}
	return nil
}

func (x *Action) GetTimeOut() uint32 {
	if x != nil && x.TimeOut != nil {
		return *x.TimeOut
	}
	return 0
}

func (x *Action) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Action) GetAuthentication() *Authentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *Action) GetBondingKey() *BleBondingKey {
	if x != nil {
		return x.BondingKey
	}
	return nil
}

func (x *Action) GetApbMac() []byte {
	if x != nil {
		return x.ApbMac
	}
	return nil
}

var File_aruba_iot_sb_action_proto protoreflect.FileDescriptor

var file_aruba_iot_sb_action_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x73, 0x62, 0x2d, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x75,
	0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x1a, 0x15, 0x61, 0x72,
	0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3d, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x62, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x79,
	0x4f, 0x6f, 0x62, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x4f, 0x6f,
	0x62, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x79, 0x4f, 0x77, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x4f, 0x77, 0x6e, 0x22, 0x96, 0x03, 0x0a, 0x06, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b,
	0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x63, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x55, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x47, 0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x72, 0x75, 0x62,
	0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3e, 0x0a, 0x0a, 0x62, 0x6f,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
	0x2e, 0x42, 0x6c, 0x65, 0x42, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x52, 0x0a,
	0x62, 0x6f, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x70,
	0x62, 0x4d, 0x61, 0x63, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x61, 0x70, 0x62, 0x4d,
	0x61, 0x63, 0x2a, 0x62, 0x0a, 0x14, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x6e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x10,
	0x01, 0x12, 0x07, 0x0a, 0x03, 0x6f, 0x6f, 0x62, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x6c, 0x65,
	0x73, 0x63, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x6c, 0x65, 0x73, 0x63,
	0x50, 0x61, 0x73, 0x73, 0x6b, 0x65, 0x79, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x6c, 0x65, 0x73,
	0x63, 0x4f, 0x6f, 0x62, 0x10, 0x05, 0x42, 0x1b, 0x5a, 0x19, 0x6c, 0x75, 0x62, 0x64, 0x75, 0x62,
	0x2e, 0x6e, 0x6c, 0x2f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f,
}

var (
	file_aruba_iot_sb_action_proto_rawDescOnce sync.Once
	file_aruba_iot_sb_action_proto_rawDescData = file_aruba_iot_sb_action_proto_rawDesc
)

func file_aruba_iot_sb_action_proto_rawDescGZIP() []byte {
	file_aruba_iot_sb_action_proto_rawDescOnce.Do(func() {
		file_aruba_iot_sb_action_proto_rawDescData = protoimpl.X.CompressGZIP(file_aruba_iot_sb_action_proto_rawDescData)
	})
	return file_aruba_iot_sb_action_proto_rawDescData
}

var file_aruba_iot_sb_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aruba_iot_sb_action_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aruba_iot_sb_action_proto_goTypes = []any{
	(AuthenticationMethod)(0), // 0: aruba_telemetry.AuthenticationMethod
	(*Authentication)(nil),    // 1: aruba_telemetry.Authentication
	(*Action)(nil),            // 2: aruba_telemetry.Action
	(ActionType)(0),           // 3: aruba_telemetry.ActionType
	(*BleBondingKey)(nil),     // 4: aruba_telemetry.BleBondingKey
}
var file_aruba_iot_sb_action_proto_depIdxs = []int32{
	0, // 0: aruba_telemetry.Authentication.method:type_name -> aruba_telemetry.AuthenticationMethod
	3, // 1: aruba_telemetry.Action.type:type_name -> aruba_telemetry.ActionType
	1, // 2: aruba_telemetry.Action.authentication:type_name -> aruba_telemetry.Authentication
	4, // 3: aruba_telemetry.Action.bondingKey:type_name -> aruba_telemetry.BleBondingKey
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aruba_iot_sb_action_proto_init() }
func file_aruba_iot_sb_action_proto_init() {
	if File_aruba_iot_sb_action_proto != nil {
		return
	}
	file_aruba_iot_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aruba_iot_sb_action_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Authentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_sb_action_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aruba_iot_sb_action_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aruba_iot_sb_action_proto_goTypes,
		DependencyIndexes: file_aruba_iot_sb_action_proto_depIdxs,
		EnumInfos:         file_aruba_iot_sb_action_proto_enumTypes,
		MessageInfos:      file_aruba_iot_sb_action_proto_msgTypes,
	}.Build()
	File_aruba_iot_sb_action_proto = out.File
	file_aruba_iot_sb_action_proto_rawDesc = nil
	file_aruba_iot_sb_action_proto_goTypes = nil
	file_aruba_iot_sb_action_proto_depIdxs = nil
}
