//  (C) Copyright [2018-2022] Hewlett Packard Enterprise Development LP
//  Note: File corresponds to AOS 8.10.x.x release

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: aruba-iot-zb-types.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Zigbee ACK result for send or action/write reqeust
type ZbResult int32

const (
	// Success
	ZbResult_SUCCEEDED ZbResult = 0
	// Generic failure
	ZbResult_FAILED ZbResult = 1
)

// Enum value maps for ZbResult.
var (
	ZbResult_name = map[int32]string{
		0: "SUCCEEDED",
		1: "FAILED",
	}
	ZbResult_value = map[string]int32{
		"SUCCEEDED": 0,
		"FAILED":    1,
	}
)

func (x ZbResult) Enum() *ZbResult {
	p := new(ZbResult)
	*p = x
	return p
}

func (x ZbResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZbResult) Descriptor() protoreflect.EnumDescriptor {
	return file_aruba_iot_zb_types_proto_enumTypes[0].Descriptor()
}

func (ZbResult) Type() protoreflect.EnumType {
	return &file_aruba_iot_zb_types_proto_enumTypes[0]
}

func (x ZbResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ZbResult) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ZbResult(num)
	return nil
}

// Deprecated: Use ZbResult.Descriptor instead.
func (ZbResult) EnumDescriptor() ([]byte, []int) {
	return file_aruba_iot_zb_types_proto_rawDescGZIP(), []int{0}
}

// Ack code for failure
type ZbAckCode int32

const (
	ZbAckCode_OK ZbAckCode = 0
)

// Enum value maps for ZbAckCode.
var (
	ZbAckCode_name = map[int32]string{
		0: "OK",
	}
	ZbAckCode_value = map[string]int32{
		"OK": 0,
	}
)

func (x ZbAckCode) Enum() *ZbAckCode {
	p := new(ZbAckCode)
	*p = x
	return p
}

func (x ZbAckCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ZbAckCode) Descriptor() protoreflect.EnumDescriptor {
	return file_aruba_iot_zb_types_proto_enumTypes[1].Descriptor()
}

func (ZbAckCode) Type() protoreflect.EnumType {
	return &file_aruba_iot_zb_types_proto_enumTypes[1]
}

func (x ZbAckCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ZbAckCode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ZbAckCode(num)
	return nil
}

// Deprecated: Use ZbAckCode.Descriptor instead.
func (ZbAckCode) EnumDescriptor() ([]byte, []int) {
	return file_aruba_iot_zb_types_proto_rawDescGZIP(), []int{1}
}

// Zigbee EPC
type ZbEPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Endpoint
	Endpoint *uint32 `protobuf:"varint,1,opt,name=endpoint" json:"endpoint,omitempty"`
	// Profile ID
	ProfileId *uint32 `protobuf:"varint,2,opt,name=profile_id,json=profileId" json:"profile_id,omitempty"`
	// Cluster ID
	ClusterId *uint32 `protobuf:"varint,3,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
}

func (x *ZbEPC) Reset() {
	*x = ZbEPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_zb_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbEPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbEPC) ProtoMessage() {}

func (x *ZbEPC) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_zb_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbEPC.ProtoReflect.Descriptor instead.
func (*ZbEPC) Descriptor() ([]byte, []int) {
	return file_aruba_iot_zb_types_proto_rawDescGZIP(), []int{0}
}

func (x *ZbEPC) GetEndpoint() uint32 {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return 0
}

func (x *ZbEPC) GetProfileId() uint32 {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return 0
}

func (x *ZbEPC) GetClusterId() uint32 {
	if x != nil && x.ClusterId != nil {
		return *x.ClusterId
	}
	return 0
}

// Zigbee E2PC
type ZbE2PC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Destination endpoint, and profile ID, cluster ID
	Destination *ZbEPC `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	// Source endpoint
	SourceEndpoint *uint32 `protobuf:"varint,2,opt,name=source_endpoint,json=sourceEndpoint" json:"source_endpoint,omitempty"`
}

func (x *ZbE2PC) Reset() {
	*x = ZbE2PC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_zb_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZbE2PC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZbE2PC) ProtoMessage() {}

func (x *ZbE2PC) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_zb_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZbE2PC.ProtoReflect.Descriptor instead.
func (*ZbE2PC) Descriptor() ([]byte, []int) {
	return file_aruba_iot_zb_types_proto_rawDescGZIP(), []int{1}
}

func (x *ZbE2PC) GetDestination() *ZbEPC {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *ZbE2PC) GetSourceEndpoint() uint32 {
	if x != nil && x.SourceEndpoint != nil {
		return *x.SourceEndpoint
	}
	return 0
}

var File_aruba_iot_zb_types_proto protoreflect.FileDescriptor

var file_aruba_iot_zb_types_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x7a, 0x62, 0x2d, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x75, 0x62,
	0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x1a, 0x15, 0x61, 0x72, 0x75,
	0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x61, 0x0a, 0x05, 0x5a, 0x62, 0x45, 0x50, 0x43, 0x12, 0x1a, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x06, 0x5a, 0x62, 0x45, 0x32, 0x50, 0x43, 0x12,
	0x38, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c,
	0x65, 0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x5a, 0x62, 0x45, 0x50, 0x43, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x2a, 0x25, 0x0a, 0x08, 0x5a, 0x62, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x55, 0x43, 0x43, 0x45, 0x45, 0x44, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x2a, 0x13, 0x0a, 0x09, 0x5a, 0x62, 0x41,
	0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x42, 0x1b,
	0x5a, 0x19, 0x6c, 0x75, 0x62, 0x64, 0x75, 0x62, 0x2e, 0x6e, 0x6c, 0x2f, 0x61, 0x72, 0x75, 0x62,
	0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_aruba_iot_zb_types_proto_rawDescOnce sync.Once
	file_aruba_iot_zb_types_proto_rawDescData = file_aruba_iot_zb_types_proto_rawDesc
)

func file_aruba_iot_zb_types_proto_rawDescGZIP() []byte {
	file_aruba_iot_zb_types_proto_rawDescOnce.Do(func() {
		file_aruba_iot_zb_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_aruba_iot_zb_types_proto_rawDescData)
	})
	return file_aruba_iot_zb_types_proto_rawDescData
}

var file_aruba_iot_zb_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aruba_iot_zb_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aruba_iot_zb_types_proto_goTypes = []any{
	(ZbResult)(0),  // 0: aruba_telemetry.ZbResult
	(ZbAckCode)(0), // 1: aruba_telemetry.ZbAckCode
	(*ZbEPC)(nil),  // 2: aruba_telemetry.ZbEPC
	(*ZbE2PC)(nil), // 3: aruba_telemetry.ZbE2PC
}
var file_aruba_iot_zb_types_proto_depIdxs = []int32{
	2, // 0: aruba_telemetry.ZbE2PC.destination:type_name -> aruba_telemetry.ZbEPC
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aruba_iot_zb_types_proto_init() }
func file_aruba_iot_zb_types_proto_init() {
	if File_aruba_iot_zb_types_proto != nil {
		return
	}
	file_aruba_iot_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aruba_iot_zb_types_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ZbEPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aruba_iot_zb_types_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ZbE2PC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aruba_iot_zb_types_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aruba_iot_zb_types_proto_goTypes,
		DependencyIndexes: file_aruba_iot_zb_types_proto_depIdxs,
		EnumInfos:         file_aruba_iot_zb_types_proto_enumTypes,
		MessageInfos:      file_aruba_iot_zb_types_proto_msgTypes,
	}.Build()
	File_aruba_iot_zb_types_proto = out.File
	file_aruba_iot_zb_types_proto_rawDesc = nil
	file_aruba_iot_zb_types_proto_goTypes = nil
	file_aruba_iot_zb_types_proto_depIdxs = nil
}
