//  (C) Copyright [2018-2022] Hewlett Packard Enterprise Development LP
//  Note: File corresponds to AOS 8.10.x.x release

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: aruba-iot-nb-characteristic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Values correspond to the different BLE GATT API transactions
// A subset of these might not be supported by certain AP types
type CharProperty int32

const (
	CharProperty_broadcast            CharProperty = 0
	CharProperty_read                 CharProperty = 1
	CharProperty_writeWithoutResponse CharProperty = 2
	CharProperty_writeWithResponse    CharProperty = 3
	CharProperty_notify               CharProperty = 4
	CharProperty_indicate             CharProperty = 5
	CharProperty_signedWrite          CharProperty = 6
	CharProperty_writeReliable        CharProperty = 7
	CharProperty_writeAux             CharProperty = 8
)

// Enum value maps for CharProperty.
var (
	CharProperty_name = map[int32]string{
		0: "broadcast",
		1: "read",
		2: "writeWithoutResponse",
		3: "writeWithResponse",
		4: "notify",
		5: "indicate",
		6: "signedWrite",
		7: "writeReliable",
		8: "writeAux",
	}
	CharProperty_value = map[string]int32{
		"broadcast":            0,
		"read":                 1,
		"writeWithoutResponse": 2,
		"writeWithResponse":    3,
		"notify":               4,
		"indicate":             5,
		"signedWrite":          6,
		"writeReliable":        7,
		"writeAux":             8,
	}
)

func (x CharProperty) Enum() *CharProperty {
	p := new(CharProperty)
	*p = x
	return p
}

func (x CharProperty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CharProperty) Descriptor() protoreflect.EnumDescriptor {
	return file_aruba_iot_nb_characteristic_proto_enumTypes[0].Descriptor()
}

func (CharProperty) Type() protoreflect.EnumType {
	return &file_aruba_iot_nb_characteristic_proto_enumTypes[0]
}

func (x CharProperty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CharProperty) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CharProperty(num)
	return nil
}

// Deprecated: Use CharProperty.Descriptor instead.
func (CharProperty) EnumDescriptor() ([]byte, []int) {
	return file_aruba_iot_nb_characteristic_proto_rawDescGZIP(), []int{0}
}

// Used to report attributes of a BLE GATT characteristic.
// used in response to characteristic discovery actions, read actions and
// asynchronously as a results of GATT notifications
type Characteristic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Refers to the MAC address of the end device. This should be a 6 byte BLE MAC
	DeviceMac []byte `protobuf:"bytes,1,opt,name=deviceMac" json:"deviceMac,omitempty"`
	// identifiers
	ServiceUuid        []byte `protobuf:"bytes,2,opt,name=serviceUuid" json:"serviceUuid,omitempty"`
	CharacteristicUuid []byte `protobuf:"bytes,3,opt,name=characteristicUuid" json:"characteristicUuid,omitempty"`
	// Value will get populated after reads/notifications/indications
	Value []byte `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	// description and properties may get populated after
	// connection / characteristic discovery
	Description *string        `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Properties  []CharProperty `protobuf:"varint,6,rep,name=properties,enum=aruba_telemetry.CharProperty" json:"properties,omitempty"`
}

func (x *Characteristic) Reset() {
	*x = Characteristic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_nb_characteristic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Characteristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Characteristic) ProtoMessage() {}

func (x *Characteristic) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_nb_characteristic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Characteristic.ProtoReflect.Descriptor instead.
func (*Characteristic) Descriptor() ([]byte, []int) {
	return file_aruba_iot_nb_characteristic_proto_rawDescGZIP(), []int{0}
}

func (x *Characteristic) GetDeviceMac() []byte {
	if x != nil {
		return x.DeviceMac
	}
	return nil
}

func (x *Characteristic) GetServiceUuid() []byte {
	if x != nil {
		return x.ServiceUuid
	}
	return nil
}

func (x *Characteristic) GetCharacteristicUuid() []byte {
	if x != nil {
		return x.CharacteristicUuid
	}
	return nil
}

func (x *Characteristic) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Characteristic) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Characteristic) GetProperties() []CharProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

var File_aruba_iot_nb_characteristic_proto protoreflect.FileDescriptor

var file_aruba_iot_nb_characteristic_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x6e, 0x62, 0x2d, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x74, 0x72, 0x79, 0x22, 0xf7, 0x01, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74,
	0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x61, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x4d, 0x61, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x55, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x63, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x55, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x12, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x55, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x3d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x74, 0x72, 0x79, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2a, 0xa4,
	0x01, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12,
	0x0d, 0x0a, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x77, 0x72, 0x69, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x10, 0x05, 0x12, 0x0f, 0x0a, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x77, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x6c,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x41, 0x75, 0x78, 0x10, 0x08, 0x42, 0x1b, 0x5a, 0x19, 0x6c, 0x75, 0x62, 0x64, 0x75, 0x62, 0x2e,
	0x6e, 0x6c, 0x2f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f,
}

var (
	file_aruba_iot_nb_characteristic_proto_rawDescOnce sync.Once
	file_aruba_iot_nb_characteristic_proto_rawDescData = file_aruba_iot_nb_characteristic_proto_rawDesc
)

func file_aruba_iot_nb_characteristic_proto_rawDescGZIP() []byte {
	file_aruba_iot_nb_characteristic_proto_rawDescOnce.Do(func() {
		file_aruba_iot_nb_characteristic_proto_rawDescData = protoimpl.X.CompressGZIP(file_aruba_iot_nb_characteristic_proto_rawDescData)
	})
	return file_aruba_iot_nb_characteristic_proto_rawDescData
}

var file_aruba_iot_nb_characteristic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aruba_iot_nb_characteristic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aruba_iot_nb_characteristic_proto_goTypes = []any{
	(CharProperty)(0),      // 0: aruba_telemetry.CharProperty
	(*Characteristic)(nil), // 1: aruba_telemetry.Characteristic
}
var file_aruba_iot_nb_characteristic_proto_depIdxs = []int32{
	0, // 0: aruba_telemetry.Characteristic.properties:type_name -> aruba_telemetry.CharProperty
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aruba_iot_nb_characteristic_proto_init() }
func file_aruba_iot_nb_characteristic_proto_init() {
	if File_aruba_iot_nb_characteristic_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aruba_iot_nb_characteristic_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Characteristic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aruba_iot_nb_characteristic_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aruba_iot_nb_characteristic_proto_goTypes,
		DependencyIndexes: file_aruba_iot_nb_characteristic_proto_depIdxs,
		EnumInfos:         file_aruba_iot_nb_characteristic_proto_enumTypes,
		MessageInfos:      file_aruba_iot_nb_characteristic_proto_msgTypes,
	}.Build()
	File_aruba_iot_nb_characteristic_proto = out.File
	file_aruba_iot_nb_characteristic_proto_rawDesc = nil
	file_aruba_iot_nb_characteristic_proto_goTypes = nil
	file_aruba_iot_nb_characteristic_proto_depIdxs = nil
}
