//  (C) Copyright [2018-2022] Hewlett Packard Enterprise Development LP
//  Note: File corresponds to AOS 8.10.x.x release

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.6.1
// source: aruba-iot-nb-serial-data.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Serial data received from known 3rd party IoT radios
type NbSerialData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Contents of the serial message
	// This is the hex bytes read from the serial device
	NbSerialPayload []byte `protobuf:"bytes,1,opt,name=nbSerialPayload" json:"nbSerialPayload,omitempty"`
	// id of 3rd party radio
	// needs to be included in any SB SerialData msgs
	NbDeviceId *string `protobuf:"bytes,2,opt,name=nbDeviceId" json:"nbDeviceId,omitempty"`
}

func (x *NbSerialData) Reset() {
	*x = NbSerialData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aruba_iot_nb_serial_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NbSerialData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NbSerialData) ProtoMessage() {}

func (x *NbSerialData) ProtoReflect() protoreflect.Message {
	mi := &file_aruba_iot_nb_serial_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NbSerialData.ProtoReflect.Descriptor instead.
func (*NbSerialData) Descriptor() ([]byte, []int) {
	return file_aruba_iot_nb_serial_data_proto_rawDescGZIP(), []int{0}
}

func (x *NbSerialData) GetNbSerialPayload() []byte {
	if x != nil {
		return x.NbSerialPayload
	}
	return nil
}

func (x *NbSerialData) GetNbDeviceId() string {
	if x != nil && x.NbDeviceId != nil {
		return *x.NbDeviceId
	}
	return ""
}

var File_aruba_iot_nb_serial_data_proto protoreflect.FileDescriptor

var file_aruba_iot_nb_serial_data_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69, 0x6f, 0x74, 0x2d, 0x6e, 0x62, 0x2d, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x5f, 0x74, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72,
	0x79, 0x22, 0x58, 0x0a, 0x0c, 0x4e, 0x62, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x62, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x6e, 0x62, 0x53, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6e,
	0x62, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6e, 0x62, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x42, 0x1b, 0x5a, 0x19, 0x6c,
	0x75, 0x62, 0x64, 0x75, 0x62, 0x2e, 0x6e, 0x6c, 0x2f, 0x61, 0x72, 0x75, 0x62, 0x61, 0x2d, 0x69,
	0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_aruba_iot_nb_serial_data_proto_rawDescOnce sync.Once
	file_aruba_iot_nb_serial_data_proto_rawDescData = file_aruba_iot_nb_serial_data_proto_rawDesc
)

func file_aruba_iot_nb_serial_data_proto_rawDescGZIP() []byte {
	file_aruba_iot_nb_serial_data_proto_rawDescOnce.Do(func() {
		file_aruba_iot_nb_serial_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_aruba_iot_nb_serial_data_proto_rawDescData)
	})
	return file_aruba_iot_nb_serial_data_proto_rawDescData
}

var file_aruba_iot_nb_serial_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aruba_iot_nb_serial_data_proto_goTypes = []any{
	(*NbSerialData)(nil), // 0: aruba_telemetry.NbSerialData
}
var file_aruba_iot_nb_serial_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aruba_iot_nb_serial_data_proto_init() }
func file_aruba_iot_nb_serial_data_proto_init() {
	if File_aruba_iot_nb_serial_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aruba_iot_nb_serial_data_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NbSerialData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aruba_iot_nb_serial_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aruba_iot_nb_serial_data_proto_goTypes,
		DependencyIndexes: file_aruba_iot_nb_serial_data_proto_depIdxs,
		MessageInfos:      file_aruba_iot_nb_serial_data_proto_msgTypes,
	}.Build()
	File_aruba_iot_nb_serial_data_proto = out.File
	file_aruba_iot_nb_serial_data_proto_rawDesc = nil
	file_aruba_iot_nb_serial_data_proto_goTypes = nil
	file_aruba_iot_nb_serial_data_proto_depIdxs = nil
}
